# WhatsApp Template v1.0
# Template específico para WhatsApp (hereda de base_chat.yaml)

version: "1.0"
source: "WhatsApp"
author: "Eduardo Gil + B"
date: "2025-11-29"
description: "Digester para WhatsApp con comprensión de grupos, emojis y multimedia"

# Heredar reglas base de chat
extends: "base_chat.yaml"

# WHATSAPP-SPECIFIC EXTRACTION
extraction:
  # Override identity (WhatsApp permite solo nombres, no @usernames)
  identity:
    patterns:
      - field: "sender"
        regex: "^[A-Z][a-z]+ [A-Z][a-z]+$"
        confidence: 0.90
        description: "WhatsApp muestra nombre completo"
      
      - field: "sender"
        regex: "^\\+\\d{1,3}\\s\\d{3}\\s\\d{3}\\s\\d{4}$"
        confidence: 0.60
        description: "Número de teléfono (contacto no guardado)"
  
  # WhatsApp-specific interests
  interests:
    keywords:
      technology:
        rust: ["rust", "🦀", "cargo", "tokio", "async", "borrow checker"]
        ai: ["AI", "LLM", "GPT", "Claude", "machine learning"]
        python: ["python", "🐍", "pandas", "numpy", "django"]
      
      music:
        genres: ["canción", "🎵", "playlist", "spotify", "música"]
      
      gaming:
        general: ["juego", "🎮", "game", "steam", "nintendo"]
    
    context_boost:
      - condition: "interest + emoji in same message"
        boost: 0.25
        description: "Emoji refuerza interés genuino"
      
      - condition: "repeated mention (>3 times in day)"
        boost: 0.35
        description: "Repetición frecuente = pasión"
      
      - condition: "midnight mention (00:00-03:00)"
        boost: 0.20
        description: "Mencionar a medianoche = deep interest"
  
  # WhatsApp group dynamics
  relationships:
    group_indicators:
      very_active_member:
        - messages_per_day: "> 20"
        - emoji_reactions: "> 10"
        - media_shared: "> 5"
      
      active_member:
        - messages_per_day: "> 10"
        - emoji_reactions: "> 5"
      
      lurker:
        - messages_per_day: "< 1"
        - reads_messages: true
    
    strength_indicators:
      very_strong:
        - daily_messages: "> 15"
        - emoji_usage: "> 8"
        - multimedia_shared: "> 3"
        - response_time: "< 2 minutes"
        description: "Comunicación muy íntima (pareja, mejor amigo)"
      
      strong:
        - daily_messages: "> 5"
        - emoji_usage: "> 3"
        - calls: "> 1 per week"
        description: "Amigos cercanos, familia"
  
  # Emotional extraction (emoji-heavy)
  emotional:
    sentiment_keywords:
      positive: 
        - "🦀"  # Rust crab = happy tech moment
        - "🎉"
        - "😊"
        - "❤️"
        - "🔥"  # Fire = excitement
        - "💯"  # 100 = complete agreement
      
      negative:
        - "😢"
        - "😞"
        - "💀"  # Skull = dead/killed by bug
        - "🤦"  # Facepalm = frustration
      
      confused:
        - "🤔"
        - "❓"
        - "🤷"  # Shrug = no idea
    
    intensity_modifiers:
      high: ["!!!", "CAPS LOCK", multiple emojis (>3)]
      medium: ["bastante", "algo"]
      low: ["un poco"]

# WHATSAPP MULTIMEDIA UNDERSTANDING
multimedia:
  image:
    significance: 0.8
    description: "Compartir imagen = momento visual significativo"
  
  video:
    significance: 0.9
    description: "Compartir video = contenido muy relevante"
  
  audio:
    significance: 0.95
    description: "Audio de voz = comunicación muy personal"
  
  document:
    significance: 0.85
    description: "Documento = información profesional/importante"

# WHATSAPP TIMING PATTERNS
temporal:
  activity_windows:
    morning: "06:00-09:00"
    work_hours: "09:00-18:00"
    evening: "18:00-22:00"
    late_night: "22:00-02:00"
    night_owl: "02:00-06:00"
  
  significance:
    late_night: 0.9  # Mensajes a medianoche = importancia alta
    work_hours: 0.6  # Durante trabajo = menos enfocado
    morning: 0.7     # Mañana = primera prioridad del día

# HYPERLINKS (WhatsApp-specific)
hyperlinks:
  enabled: true
  expand_short_urls: true
  
  # WhatsApp users comparten muchos links
  significance_boost: 1.2
  
  intent_inference:
    self_reference:
      patterns: 
        - "shared to myself"
        - "para mi"
        - "save"
        - "revisar luego"
        - "recordar"
      confidence: 0.95
      description: "Self-shares muy comunes en WhatsApp"
    
    recommendation:
      patterns:
        - "mira esto"
        - "deberías ver"
        - "te recomiendo"
        - "check this"
      confidence: 0.90
    
    urgent_share:
      patterns:
        - "!!!"
        - "urgente"
        - "ahora"
      confidence: 0.85

# WHATSAPP FORMAT PARSING
format:
  timestamp_pattern: "\\[(\\d{2}/\\d{2}/\\d{4}, \\d{2}:\\d{2}:\\d{2})\\]"
  sender_pattern: "([^:]+):"
  message_pattern: ": (.+)"
  
  # WhatsApp system messages
  system_messages:
    - "Messages and calls are end-to-end encrypted"
    - "created group"
    - "changed the subject"
    - "added"
    - "left"

# PERFORMANCE (WhatsApp puede tener muchos mensajes)
performance:
  batch_size: 200  # Aumentado vs base (100)
  parallel_extraction: true
  cache_enabled: true
  max_group_size: 50000  # Grupos muy grandes

# QUALITY THRESHOLDS
quality:
  min_message_length: 2  # "ok" es válido
  min_confidence: 0.6    # WhatsApp data es menos formal
  skip_system_messages: true
